<?php
require_once "includes/DataAccess.php";
require_once "includes/validation.php";
session_start();

if(!isset($_SESSION['u_id']) || !isset($_SESSION['u_name'])){
  header("Location: index.php");
}

$da=new DataAccess();

date_default_timezone_set("Asia/Dhaka");
    $time= date("h:i:s a");
    $date= date("d-M-Y");


$users_query="select u_id, u_name, u_role from users";
$users_rows=$da->ExecuteQuery($users_query);
$users_rowCount=0;



if($_SERVER['REQUEST_METHOD']=="POST"){
  // if (isset($_POST['u_search'])) {
  //   $fieldsArr=["u_name"];
  //   if (!validateFieldName($fieldsArr, $_POST)) {
  //     $_SESSION['msg']="Field names are not matching!";
  //     $_SESSION['msg_type']="danger";
  //   }
  //   else{
  //     if(!validateString($_POST['u_name'])){
  //       $_SESSION['msg']="Search box can not be empty!";
  //       $_SESSION['msg_type']="danger"; 
  //     }
  //     else{
  //       $users_query="select * from users where u_name like '%".$_POST['u_name']."%'";
  //       $users_rows=$da->ExecuteQuery($users_query);
  //       $n=$da->GetTotalNumberOfRows($users_query);
      
  //       if($n>1){ $_SESSION['msg']=$n." results found!";}
  //       else{$_SESSION['msg']=$n." result found!";}

  //       $_SESSION['msg_type']="success"; 
  //     }
  //   }

  // }


  if (isset($_POST['s_amount_update'])) {
    $fieldsArr=["s_amount"];
    if (!validateFieldName($fieldsArr, $_POST)) {
      $_SESSION['msg']="Field names are not matching!";
      $_SESSION['msg_type']="danger";
    }
    else{
      if(!validateNumeric($_POST['s_amount'])){
        $_SESSION['msg']="Please enter a valid amount first!";
        $_SESSION['msg_type']="danger";
        $s_amount_update_visible="off";
      }
      else{
        if(!empty($_SESSION['s_u_id'])){
        	$checkquery="select * from salary where u_id='".$_SESSION['s_u_id']."'";
        	//insert
	        if ($da->GetTotalNumberOfRows($checkquery)<1) {
	          $query="insert into salary (s_id, u_id, s_amount) VALUES ('".'s-'.$da->AutoGeneratedId('salary','s_id')."','".$_SESSION['s_u_id']."',".$_POST['s_amount'].")";
	          if(!$da->ExecuteQuery($query)){
	            $_SESSION['msg']="'".$_SESSION['s_u_id']."' salary insertion failed!";
	            $_SESSION['msg_type']="danger";
	          }
	          else{
	            $_SESSION['msg']="'".$_SESSION['s_u_id']."' salary inserted successfully!";
	            $_SESSION['msg_type']="success";
	          }
	        }
	        //update
	        else{
	          $query="update salary set s_amount='".$_POST['s_amount']."' WHERE u_id='".$_SESSION['s_u_id']."'";
	          if(!$da->ExecuteQuery($query)){
	            $_SESSION['msg']="'".$_SESSION['s_u_id']."' salary update failed!";
	            $_SESSION['msg_type']="danger";
	          }
	          else{
	            $_SESSION['msg']="'".$_SESSION['s_u_id']."' salary updated successfully!";
	            $_SESSION['msg_type']="success";
	          }
	        }
	        unset($_SESSION['s_u_id']);
	        $s_amount_update_visible="off";
	    }
	    else{
	    	$_SESSION['msg']="Salary update failed! Invalid u_id. Please Select a Row First !";
	        $_SESSION['msg_type']="danger";
	    }
	  }

    }
      
    
      
   }



}




if($_SERVER['REQUEST_METHOD']=="GET"){
  if (isset($_GET['s_u_id'])) {
      $_SESSION['s_u_id']=$_GET['s_u_id'];
  }
}
?>






<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!-- font awesome -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">



    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/salary.css">


    <title>Salary</title>
  </head>
  <body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark" id="nav">
        <div class="container">
            <a class="navbar-brand text-white" href="adminHome.php"><i id="logo"></i><b>Payroll System</b></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nav">
                <ul class="navbar-nav ml-auto">
                   
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                         <i class="fa fa-user"></i> <?php echo $_SESSION['u_name']; ?>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" >
                          <a class="dropdown-item" href="changePassword.php"><i class="fas fa-exchange-alt"></i>Change Password</a>
                          <a class="dropdown-item" href="logout.php"><i class="fas fa-sign-out-alt"></i>Logout</a>
                        </div>
                    </li>



                    <li class="nav-item ">
                        <a class="nav-link " href="#"><i class="fa fa-clock-o" aria-hidden="true"></i><?php echo $time; ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="#"><i class="fa fa-calendar" aria-hidden="true"></i><?php echo $date; ?></a>
                    </li>
                   
                </ul>


            </div>
        </div>
        </nav>
    </header>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
         <li class="breadcrumb-item"><a href="adminHome.php">Home</a></li>
         <li class="breadcrumb-item active" aria-current="page">Salary</li>
         </ol>
    </nav>


    <?php if (isset($_SESSION["msg"])) { ?>
      <div class="my-0 alert alert-<?=$_SESSION['msg_type']?>" role="alert">
          <?php
            echo $_SESSION['msg'];
            unset($_SESSION['msg']);
            unset($_SESSION['msg_type']);
          ?>
      </div>

      <?php } ?>





	


<!-- <form method="POST" action="addEditUsers.php" class="d-inline-block">
	<button type="submit" name="addUsers" value="#autogenerated-id" onclick="window.location.href='addEditUsers.php'"  class="btn btn-success m-0 mt-4"><i class="fa fa-plus" aria-hidden="true"></i></button>
</form> -->


<div class="container-fluid">


<form class="d-flex justify-content-center mt-5" action="<?php echo $_SERVER['PHP_SELF']; ?> " method="POST">
          <label class="mr-2 col-form-label font-weight-bold">User ID:</label>
          <label class="mr-4 col-form-label text-danger"><?php 
            if (isset($_GET['s_u_id'])) {
              echo $_GET['s_u_id']; 
            }
            else{
              echo "XXXXX.xxx";
            } ?>
          </label>
          <div class="form-group mb-2">
            <input type="text" name="s_amount" class="form-control" id="inputPassword2" placeholder="amount">
          </div>
          <button type="submit" name="s_amount_update" class="btn btn-warning mb-2 ml-2" <?php if(isset($s_amount_update_visible)){echo "disabled";}?> >Update</button>
      </form>



<button type="button"  onclick="window.location.href='salary.php'"  class="btn btn-primary m-0 mt-0" id="refresh"><i class="fa fa-refresh" aria-hidden="true"></i>Refresh </button>

<form id="users_search_form" class="form-inline float-right mt-0 mb-0" action="<?php echo $_SERVER['PHP_SELF']; ?> " method="POST">
  <div class="form-group mb-2">
    <input type="text" name="u_name" class="form-control" id="inputPassword2" placeholder="Search by name">
  </div>
  <button type="submit" name="u_search" class="btn btn-info mb-2 ml-2"><i class="fa fa-search" aria-hidden="true"></i></button>
</form>

<script type="text/javascript">
  var users_search_form= document.getElementById('users_search_form');
  users_search_form.onsubmit=function(){
    var u_name=document.getElementsByTagName('input')[1].value;
    if(u_name==null || u_name==""){
      swal("Search Failed !", "Name field must be filled out !", "error");
      return false;
    }
  }  
</script>



<table class="table table-hover">
  <thead class="">
    <tr>
      <th scope="col">#</th>
      <th scope="col">u_id</th>
      <th scope="col">u_name</th>
      <th scope="col">u_role</th>
      <th scope="col">s_id</th>
      <th scope="col">s_amount</th>
      <th scope="col">Edit Salary</th>
    </tr>
  </thead>

  <tbody>
      <?php while($users_arr = $da->ConvertRowsToArray($users_rows)){ 
          $users_rowCount++; 
          // ----------salary----------
          $salary_query="select s_id, s_amount from salary where u_id='".$users_arr['u_id']."'";
          $salary_rows=$da->ExecuteQuery($salary_query);
          $salary_arr = $da->ConvertRowsToArray($salary_rows);
          // ----------salary----------
      ?>
    <tr>
      <th scope="row"><?php if(isset($users_arr)){echo $users_rowCount;} ?></th>
      <td><?php if(isset($users_arr)){echo $users_arr['u_id'];} ?></td>
      <td><?php if(isset($users_arr)){echo $users_arr['u_name'];} ?></td>
      <td><?php if(isset($users_arr)){echo $users_arr['u_role'];} ?></td>

      <!-- ----------salary---------- -->
      <td><?php if(isset($salary_arr)){echo $salary_arr['s_id'];} else{echo "-";} ?></td> 
      <td><?php if(isset($salary_arr)){echo $salary_arr['s_amount'];} else{echo "-";} ?></td> 
      <!-- ----------salary---------- -->

      <td><a href="salary.php?s_u_id=<?php echo $users_arr['u_id']?>"><i class="fa fa-pencil text-warning" aria-hidden="true"></i></a></td>

    </tr>
      <?php } ?>
  </tbody>

</table>

</div>


        

<script type="text/javascript">

      document.getElementsByName('u_name')[0].addEventListener('keyup',loadResponseGet);
     document.getElementsByName('u_search')[0].addEventListener('click',loadResponseGet);

      function loadResponseGet(){
        var u_name = document.getElementsByName('u_name')[0].value;
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'salarySearchAjax.php?u_name='+u_name, true);
        xhr.send();
        xhr.onload = function(){
            if(xhr.status == 200){
                document.getElementsByTagName('tbody')[0].innerHTML = this.responseText;
            }
            else if(this.status == 404){
              document.getElementsByTagName('tbody')[0].innerHTML = "404 - NOT FOUND!";
            }
        };
      }
</script>




    <!-- Optional JavaScript -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>