<?php
class DataAccess
{
	private $conn;
	public function __construct(){
		$serverName = "localhost";
		$userName = "root";
		$password = "";
		$dbName = "payrolldb";

		$this->conn = mysqli_connect($serverName, $userName, $password, $dbName);

		if(mysqli_connect_errno()){
		  echo "Error: " . mysqli_connect_err();
		  die();
		}
	}

	public function ExecuteQuery($query){
		return mysqli_query($this->conn, $query);

	}

	public function ConvertRowsToArray($ExecutedQuery){
		return mysqli_fetch_assoc($ExecutedQuery);
	}

	public function GetTotalNumberOfRows($query){
		return mysqli_num_rows($this->ExecuteQuery($query));
	}

	public function AutoGeneratedId($table_name,$key){
		$query="select ".$key." from ".$table_name." ORDER BY ".$key." DESC LIMIT 1";	
		
		$row=mysqli_fetch_assoc($this->ExecuteQuery($query));
		if(isset($row)){
			$arrId=explode('-', $row[$key]);
			$id=$arrId[1]+1;
		}
		else{
			$id=1;	
		}
		
		$id=sprintf("%04s", $id);
		return $id;
	}

}
?>
